FROM mariadb
COPY ./bdd.sql /var/bdd.sql
#RUN mysql -u"root" -p="root" -h"" < /var/bdd.sql
#RUN apt-get update && apt-get -y install mysql-client
#CMD mysql -u"root" -p"root" -h"localhost" < /var/bdd.sql